import img1 from '../images/Product1.svg';
import img2 from '../images/Product2.svg';
import img3 from '../images/Product3.svg';
import img4 from '../images/Product4.svg';
import img5 from '../images/Product5.webp';
import img6 from '../images/Product6.webp';
import img7 from '../images/Product7.webp';
import img8 from '../images/Product8.webp';
import img9 from '../images/img10.svg';
import img10 from '../images/img11.svg';
import img11 from  '../images/img12.svg';
import img12 from  '../images/img13.svg';
import img13 from  '../images/img14.svg';
import new1 from '../images/Newpic1.svg';
import opic2 from '../images/opic2.svg';
import opic3 from '../images/opic3.svg';

const products = [
  {
    id: 1,
    name: 'King’s Delight Sofa',
    price: 550.00,
    pic: img1,
    opic: [img1],
    category: 'Living Room',
    review: 12,
    rating: 4.25,
    description: 'Transform your living space with the timeless elegance of our Chateau Armchair. This exquisite piece blends classic design with modern comfort, making it a perfect addition to any home.',
  },
  {
    id: 2,
    name: 'Royal Comfort Bed',
    price: 750.00,
    pic: img2,
    opic: [img2],
    category: 'Bedroom',
    review: 8,
    rating: 4.0,
    description: 'Indulge in luxurious comfort with our Royal Comfort Bed. Crafted with premium materials and exquisite detailing, it promises a restful night’s sleep in unparalleled style.',
  },
  {
    id: 3,
    name: 'Cosmic Dining Table',
    price: 420.00,
    pic: img3,
    opic: [img3],
    category: 'Dining Room',
    review: 10,
    rating: 4.5,
    description: 'Create unforgettable dining experiences with our Cosmic Dining Table. Its sleek, minimalist design and durable construction make it a perfect centerpiece for modern homes.',
  },
  {
    id: 4,
    name: 'Elegant Lounge Chair',
    price: 320.00,
    pic: img4,
    opic: [img4],
    category: 'Living Room',
    review: 6,
    rating: 4.0,
    description: 'Enhance your relaxation space with our Elegant Lounge Chair. With its ergonomic design and plush cushioning, it offers both comfort and sophistication.',
  },
  {
    id: 5,
    name: 'Zen Garden Sofa Set',
    price: 980.00,
    pic: img5,
    opic: [img5],
    category: 'Bedroom',
    review: 15,
    rating: 4.8,
    description: 'Transform your outdoor oasis with our Zen Garden Sofa Set. Crafted for durability and style, it brings tranquility and luxury to your garden or patio.',
  },
  {
    id: 6,
    name: 'Vintage Bookshelf',
    price: 280.00,
    pic: img6,
    opic: [new1, opic2, opic3],
    category: 'Bedroom',
    review: 20,
    rating: 4.7,
    description: 'Organize your books in style with our Vintage Bookshelf. Its classic design and sturdy build make it a charming addition to any study or living room.',
  },
  {
    id: 7,
    name: 'New Sofa Plus',
    price: 250.00,
    pic: img7,
    opic: [img7],
    category: 'Table',
    review: 12,
    rating: 4.25,
    description: 'Transform your living space with the timeless elegance of our Chateau Armchair. This exquisite piece blends classic design with modern comfort, making it a perfect addition to any home.',
  },
  {
    id: 8,
    name: 'Comfortable Couch',
    price: 460.00,
    pic: img8,
    opic: [img8],
    category: 'Bedroom',
    review: 8,
    rating: 4.0,
    description: 'Indulge in luxurious comfort with our Royal Comfort Bed. Crafted with premium materials and exquisite detailing, it promises a restful night’s sleep in unparalleled style.',
  },
  {
    id: 9,
    name: 'Garden Chair',
    price: 420.00,
    pic: img9,
    opic: [img9],
    category: 'Dining Room',
    review: 10,
    rating: 4.5,
    description: 'Create unforgettable dining experiences with our Cosmic Dining Table. Its sleek, minimalist design and durable construction make it a perfect centerpiece for modern homes.',
  },
  {
    id: 10,
    name: 'Elegant Lounge Table',
    price: 200.00,
    pic: img10,
    opic: [img10],
    category: 'Living Room',
    review: 6,
    rating: 4.0,
    description: 'Enhance your relaxation space with our Elegant Lounge Chair. With its ergonomic design and plush cushioning, it offers both comfort and sophistication.',
  },
  {
    id: 11,
    name: 'Cabinet',
    price: 980.00,
    pic: img11,
    opic: [img11],
    category: 'Bedroom',
    review: 15,
    rating: 4.8,
    description: 'Transform your outdoor oasis with our Zen Garden Sofa Set. Crafted for durability and style, it brings tranquility and luxury to your garden or patio.',
  },
  {
    id: 12,
    name: 'King’s Bed',
    price: 280.00,
    pic: img12,
    opic: [12],
    category: 'Bedroom',
    review: 20,
    rating: 4.7,
    description: 'Organize your books in style with our Vintage Bookshelf. Its classic design and sturdy build make it a charming addition to any study or living room.',
  },

{
  id: 13,
  name: 'Luxury Ottoman',
  price: 300.00,
  pic: img3,
  opic: [img3],
  category: 'Living Room',
  review: 18,
  rating: 4.5,
  description: 'Add a touch of luxury to your living space with our plush Ottoman. Perfect for putting your feet up or as an extra seating option.',
},
{
  id: 14,
  name: 'Modern Coffee Table',
  price: 150.00,
  pic: img10,
  opic: [img10],
  category: 'Living Room',
  review: 25,
  rating: 4.9,
  description: 'Bring a contemporary feel to your home with our Modern Coffee Table. Sleek lines and a sturdy design make it both stylish and functional.',
},
{
  id: 15,
  name: 'Classic Nightstand',
  price: 120.00,
  pic: img5,
  opic: [img5],
  category: 'Bedroom',
  review: 14,
  rating: 4.4,
  description: 'Keep your essentials close at hand with our Classic Nightstand. Its timeless design and practical features make it a bedroom must-have.',
},
{
  id: 16,
  name: 'Ergonomic Office Chair',
  price: 220.00,
  pic: img7,
  opic: [img7],
  category: 'Office',
  review: 30,
  rating: 4.6,
  description: 'Work comfortably with our Ergonomic Office Chair. Designed to provide optimal support and reduce strain during long hours of work.',
},
{
  id: 17,
  name: 'Outdoor Patio Set',
  price: 680.00,
  pic: img1,
  opic: [img1],
  category: 'Outdoor',
  review: 22,
  rating: 4.8,
  description: 'Enjoy your outdoor space with our stylish and durable Patio Set. Perfect for entertaining guests or relaxing with family.',
},
{
  id: 18,
  name: 'Elegant Wardrobe',
  price: 950.00,
  pic: img6,
  opic: [img6],
  category: 'Bedroom',
  review: 12,
  rating: 4.3,
  description: 'Organize your clothes in style with our Elegant Wardrobe. Its spacious design and elegant finish make it a perfect addition to any bedroom.',
},
{
  id: 19,
  name: 'Minimalist TV Stand',
  price: 210.00,
  pic: img9,
  opic: [img9],
  category: 'Living Room',
  review: 17,
  rating: 4.1,
  description: 'Keep your living room organized with our Minimalist TV Stand. Its sleek design and practical storage options make it both stylish and functional.',
},
{
  id: 20,
  name: 'Luxury Dressing Table',
  price: 450.00,
  pic: img11,
  opic: [img11],
  category: 'Bedroom',
  review: 13,
  rating: 4.7,
  description: 'Get ready in style with our Luxury Dressing Table. Its elegant design and practical features make it a perfect addition to your bedroom.',
},
{
  id: 21,
  name: 'Comfort Recliner',
  price: 380.00,
  pic: img8,
  opic: [img8],
  category: 'Living Room',
  review: 26,
  rating: 4.6,
  description: 'Relax in ultimate comfort with our Comfort Recliner. Its ergonomic design and plush cushioning make it the perfect spot to unwind.',
},
{
  id: 22,
  name: 'Modern Bookshelf',
  price: 270.00,
  pic: img4,
  opic: [img4],
  category: 'Office',
  review: 19,
  rating: 4.5,
  description: 'Organize your books and decor with our Modern Bookshelf. Its sleek design and sturdy construction make it a practical and stylish addition to any room.',
},
{
  id: 23,
  name: 'Contemporary Dining Set',
  price: 750.00,
  pic: img12,
  opic: [img12],
  category: 'Dining Room',
  review: 21,
  rating: 4.7,
  description: 'Dine in style with our Contemporary Dining Set. Its modern design and durable materials make it perfect for both everyday meals and special occasions.',
},
{
  id: 24,
  name: 'Classic Armchair',
  price: 310.00,
  pic: img2,
  opic: [img2],
  category: 'Living Room',
  review: 11,
  rating: 4.2,
  description: 'Add a touch of elegance to your living space with our Classic Armchair. Its timeless design and comfortable seating make it a perfect addition to any home.',
},
{
  id: 25,
  name: 'Vintage Console Table',
  price: 260.00,
  pic: img5,
  opic: [img5],
  category: 'Hallway',
  review: 15,
  rating: 4.4,
  description: 'Bring a vintage charm to your hallway with our Console Table. Its classic design and practical storage make it both stylish and functional.',
},
{
  id: 26,
  name: 'Luxury King Bed',
  price: 800.00,
  pic: img10,
  opic: [img10],
  category: 'Bedroom',
  review: 18,
  rating: 4.8,
  description: 'Experience the ultimate in luxury with our King Bed. Its premium materials and elegant design promise a restful and stylish night’s sleep.',
},
{
  id: 27,
  name: 'Rustic Coffee Table',
  price: 140.00,
  pic: img1,
  opic: [img1],
  category: 'Living Room',
  review: 22,
  rating: 4.1,
  description: 'Add a rustic touch to your living space with our Coffee Table. Its sturdy construction and charming design make it a perfect addition to any home.',
},
{
  id: 28,
  name: 'Modern Bedside Table',
  price: 130.00,
  pic: img3,
  opic: [img3],
  category: 'Bedroom',
  review: 16,
  rating: 4.5,
  description: 'Keep your essentials within reach with our Modern Bedside Table. Its sleek design and practical storage make it a must-have for any bedroom.',
},
{
  id: 29,
  name: 'Luxury Chaise Lounge',
  price: 600.00,
  pic: img7,
  opic: [img7],
  category: 'Living Room',
  review: 20,
  rating: 4.7,
  description: 'Relax in style with our Luxury Chaise Lounge. Its elegant design and plush cushioning make it the perfect addition to any living space.',
},
{
  id: 30,
  name: 'Classic Dresser',
  price: 520.00,
  pic: img12,
  opic: [img12],
  category: 'Bedroom',
  review: 14,
  rating: 4.6,
  description: 'Organize your clothes and accessories with our Classic Dresser. Its timeless design and ample storage space make it a perfect addition to any bedroom.',
}

];

export default products;
