import img1 from '../images/Product1.svg';
import img2 from '../images/Product2.svg';
import img3 from '../images/Product3.svg';
import img4 from '../images/Product4.svg';
import img5 from '../images/Product5.svg';
import img6 from '../images/Product6.svg';
import new1 from '../images/Newpic1.svg';
import opic2 from '../images/opic2.svg';
import opic3 from '../images/opic3.svg';

const products = [
  {
    id: 1,
    name: 'King’s Delight Sofa',
    price: 550.00,
    pic: img1,
    opic: [img1],
    category: 'Living Room',
    review: 12,
    rating: 4.25,
    description: 'Transform your living space with the timeless elegance of our Chateau Armchair. This exquisite piece blends classic design with modern comfort, making it a perfect addition to any home.',
  },
  {
    id: 2,
    name: 'Royal Comfort Bed',
    price: 750.00,
    pic: img2,
    opic: [img2],
    category: 'Bedroom',
    review: 8,
    rating: 4.0,
    description: 'Indulge in luxurious comfort with our Royal Comfort Bed. Crafted with premium materials and exquisite detailing, it promises a restful night’s sleep in unparalleled style.',
  },
  {
    id: 3,
    name: 'Cosmic Dining Table',
    price: 420.00,
    pic: img3,
    opic: [img3],
    category: 'Dining Room',
    review: 10,
    rating: 4.5,
    description: 'Create unforgettable dining experiences with our Cosmic Dining Table. Its sleek, minimalist design and durable construction make it a perfect centerpiece for modern homes.',
  },
  {
    id: 4,
    name: 'Elegant Lounge Chair',
    price: 320.00,
    pic: img4,
    opic: [img4],
    category: 'Living Room',
    review: 6,
    rating: 4.0,
    description: 'Enhance your relaxation space with our Elegant Lounge Chair. With its ergonomic design and plush cushioning, it offers both comfort and sophistication.',
  },
  {
    id: 5,
    name: 'Zen Garden Sofa Set',
    price: 980.00,
    pic: img5,
    opic: [img5],
    category: 'Outdoor',
    review: 15,
    rating: 4.8,
    description: 'Transform your outdoor oasis with our Zen Garden Sofa Set. Crafted for durability and style, it brings tranquility and luxury to your garden or patio.',
  },
  {
    id: 6,
    name: 'Vintage Bookshelf',
    price: 280.00,
    pic: img6,
    opic: [new1, opic2, opic3],
    category: 'Study',
    review: 20,
    rating: 4.7,
    description: 'Organize your books in style with our Vintage Bookshelf. Its classic design and sturdy build make it a charming addition to any study or living room.',
  },
  {
    id: 7,
    name: 'King’s Delight Sofa',
    price: 550.00,
    pic: img1,
    opic: [img1],
    category: 'Living Room',
    review: 12,
    rating: 4.25,
    description: 'Transform your living space with the timeless elegance of our Chateau Armchair. This exquisite piece blends classic design with modern comfort, making it a perfect addition to any home.',
  },
  {
    id: 8,
    name: 'Royal Comfort Bed',
    price: 750.00,
    pic: img2,
    opic: [img2],
    category: 'Bedroom',
    review: 8,
    rating: 4.0,
    description: 'Indulge in luxurious comfort with our Royal Comfort Bed. Crafted with premium materials and exquisite detailing, it promises a restful night’s sleep in unparalleled style.',
  },
  {
    id: 9,
    name: 'Cosmic Dining Table',
    price: 420.00,
    pic: img3,
    opic: [img3],
    category: 'Dining Room',
    review: 10,
    rating: 4.5,
    description: 'Create unforgettable dining experiences with our Cosmic Dining Table. Its sleek, minimalist design and durable construction make it a perfect centerpiece for modern homes.',
  },
  {
    id: 10,
    name: 'Elegant Lounge Chair',
    price: 320.00,
    pic: img4,
    opic: [img4],
    category: 'Living Room',
    review: 6,
    rating: 4.0,
    description: 'Enhance your relaxation space with our Elegant Lounge Chair. With its ergonomic design and plush cushioning, it offers both comfort and sophistication.',
  },
  {
    id: 11,
    name: 'Zen Garden Sofa Set',
    price: 980.00,
    pic: img5,
    opic: [img5],
    category: 'Outdoor',
    review: 15,
    rating: 4.8,
    description: 'Transform your outdoor oasis with our Zen Garden Sofa Set. Crafted for durability and style, it brings tranquility and luxury to your garden or patio.',
  },
  {
    id: 12,
    name: 'Vintage Bookshelf',
    price: 280.00,
    pic: img6,
    opic: [new1, opic2, opic3],
    category: 'Study',
    review: 20,
    rating: 4.7,
    description: 'Organize your books in style with our Vintage Bookshelf. Its classic design and sturdy build make it a charming addition to any study or living room.',
  },
  {
    id: 13,
    name: 'King’s Delight Sofa',
    price: 550.00,
    pic: img1,
    opic: [img1],
    category: 'Living Room',
    review: 12,
    rating: 4.25,
    description: 'Transform your living space with the timeless elegance of our Chateau Armchair. This exquisite piece blends classic design with modern comfort, making it a perfect addition to any home.',
  },
  {
    id: 14,
    name: 'Royal Comfort Bed',
    price: 750.00,
    pic: img2,
    opic: [img2],
    category: 'Bedroom',
    review: 8,
    rating: 4.0,
    description: 'Indulge in luxurious comfort with our Royal Comfort Bed. Crafted with premium materials and exquisite detailing, it promises a restful night’s sleep in unparalleled style.',
  },
  {
    id: 15,
    name: 'Cosmic Dining Table',
    price: 420.00,
    pic: img3,
    opic: [img3],
    category: 'Dining Room',
    review: 10,
    rating: 4.5,
    description: 'Create unforgettable dining experiences with our Cosmic Dining Table. Its sleek, minimalist design and durable construction make it a perfect centerpiece for modern homes.',
  },
  {
    id: 16,
    name: 'Elegant Lounge Chair',
    price: 320.00,
    pic: img4,
    opic: [img4],
    category: 'Living Room',
    review: 6,
    rating: 4.0,
    description: 'Enhance your relaxation space with our Elegant Lounge Chair. With its ergonomic design and plush cushioning, it offers both comfort and sophistication.',
  },
  {
    id: 17,
    name: 'Zen Garden Sofa Set',
    price: 980.00,
    pic: img5,
    opic: [img5],
    category: 'Outdoor',
    review: 15,
    rating: 4.8,
    description: 'Transform your outdoor oasis with our Zen Garden Sofa Set. Crafted for durability and style, it brings tranquility and luxury to your garden or patio.',
  },
  {
    id: 18,
    name: 'Vintage Bookshelf',
    price: 280.00,
    pic: img6,
    opic: [new1, opic2, opic3],
    category: 'Study',
    review: 20,
    rating: 4.7,
    description: 'Organize your books in style with our Vintage Bookshelf. Its classic design and sturdy build make it a charming addition to any study or living room.',
  },
  {
    id: 19,
    name: 'King’s Delight Sofa',
    price: 550.00,
    pic: img1,
    opic: [img1],
    category: 'Living Room',
    review: 12,
    rating: 4.25,
    description: 'Transform your living space with the timeless elegance of our Chateau Armchair. This exquisite piece blends classic design with modern comfort, making it a perfect addition to any home.',
  },
  {
    id: 20,
    name: 'Royal Comfort Bed',
    price: 750.00,
    pic: img2,
    opic: [img2],
    category: 'Bedroom',
    review: 8,
    rating: 4.0,
    description: 'Indulge in luxurious comfort with our Royal Comfort Bed. Crafted with premium materials and exquisite detailing, it promises a restful night’s sleep in unparalleled style.',
  },
  {
    id: 21,
    name: 'Cosmic Dining Table',
    price: 420.00,
    pic: img3,
    opic: [img3],
    category: 'Dining Room',
    review: 10,
    rating: 4.5,
    description: 'Create unforgettable dining experiences with our Cosmic Dining Table. Its sleek, minimalist design and durable construction make it a perfect centerpiece for modern homes.',
  },
  {
    id: 22,
    name: 'Elegant Lounge Chair',
    price: 320.00,
    pic: img4,
    opic: [img4],
    category: 'Living Room',
    review: 6,
    rating: 4.0,
    description: 'Enhance your relaxation space with our Elegant Lounge Chair. With its ergonomic design and plush cushioning, it offers both comfort and sophistication.',
  },
  {
    id: 23,
    name: 'Zen Garden Sofa Set',
    price: 980.00,
    pic: img5,
    opic: [img5],
    category: 'Outdoor',
    review: 15,
    rating: 4.8,
    description: 'Transform your outdoor oasis with our Zen Garden Sofa Set. Crafted for durability and style, it brings tranquility and luxury to your garden or patio.',
  },
  {
    id: 24,
    name: 'Vintage Bookshelf',
    price: 280.00,
    pic: img6,
    opic: [new1, opic2, opic3],
    category: 'Study',
    review: 20,
    rating: 4.7,
    description: 'Organize your books in style with our Vintage Bookshelf. Its classic design and sturdy build make it a charming addition to any study or living room.',
  },
];

export default products;
